# osc listen address, if empty then disable osc server
address = "127.0.0.1:10001"
widget_id = "<PulsoidWidgetID>"
# only send heart rate to these avatars, if empty then send to all avatars
enable_avatars = [
    "<AvatarID>",
]

# osc parameters, if empty then not send message
#   range: heart rage 0~254 map to -1.0f~1.0f
float_parameter_name = "OSC_HeartRate_Float"
#   range: heart range 0~255
int_parameter_name = "OSC_HeartRate_Int"

vrchat.port = 9000

# trace, debug, info, warn, error, fatal, panic, disabled
logger.level = "info"
