address = "127.0.0.1:10001"
widget_id = "<PulsoidWidgetID>"
enable_avatars = [
    "<AvatarID>",
]
parameter_name = "OSC_HeartRate"

[vrchat]
port = 9000

[logger]
# trace, debug, info, warn, error, fatal, panic, disabled
level = "info"
